name: babblelon
description: A mobile game built with Flutter and Flame engine
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.28.0
  flame_audio: ^2.6.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  supabase_flutter: ^2.0.0
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flame_riverpod: ^5.4.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner:
  riverpod_generator: ^2.3.3
  analyzer: ^5.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/background/
    - assets/images/player/
    - assets/images/npcs/
    - assets/images/ui/
    - assets/audio/
    - .env 