name: babblelon
description: A mobile game built with Flutter and Flame engine
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.17.0
  flame_audio: ^2.6.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  supabase_flutter: ^2.0.0
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flame_riverpod: ^5.4.15
  google_fonts: ^6.2.1
  just_audio: ^0.9.36
  flutter_sound: ^9.28.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  http: ^1.2.1
  audioplayers: ^5.2.1
  record: ^5.0.5
  flutter_svg: ^2.2.0
  flame_rive: ^1.10.15
  http_parser: ^4.0.2
  vector_math: ^2.1.4
  flutter_animate: ^4.5.2
  lottie: ^3.3.1
  animated_text_kit: ^4.2.2
  newton_particles: ^0.2.2
  animated_flip_counter: ^0.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner:
  riverpod_generator: ^2.3.3
  riverpod_annotation: ^2.3.5
  analyzer: ^5.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/background/
    - assets/images/player/
    - assets/images/npcs/
    - assets/images/ui/
    - assets/images/items/
    - assets/audio/npc/
    - assets/audio/bg/
    - assets/audio/soundeffects/
    - assets/audio/beginner_food_vocabulary/
    - assets/images/bosses/tuktuk/
    - assets/data/
    - assets/lottie/
    - .env 